pull_request_rules:
  - name: Automatic merge on CI success and label
    conditions:
      - status-success="TypeScript to Lua Build and Validation"
      - label=automerge
    actions:
      merge:
        method: merge
