name: TypeScript to Lua Build and Validation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-validate:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm run build

      - name: Install TIC-80
        run: |
          wget https://github.com/nesbox/TIC-80/releases/download/v1.0.2164/tic80-v1.0-linux.deb
          sudo dpkg -i tic80-v1.0-linux.deb

      - name: Validate Lua files
        run: |
          OUTPUT=$(tic80 .\index.lua)
          ERROR=$(echo "$OUTPUT" | awk -F'>' '/>/ {print $2}')
          if [[ -n "$ERROR" ]]; then
            echo "Validation failed."
            echo "Error: $ERROR"
            exit 1
          else
            echo "Validation succeeded."
          fi
